"""ONITSIR · Shackle v2 — the unified Governor layer.

This module fuses THREE independent SHACKLE implementations found across the
Fame510 portfolio into ONE canonical governance surface (see architecture
doc section 1, "Same governance concept, three implementations"):

  - ONITSIR/onitsir/shackle.py        -> pure decide() + hash-chained AuditLedger
  - ADROS/backend/cognitive/shackle.py -> declarative JSON-rule veto engine
  - AgentOmega/app/shackle.py          -> DenyReason/HitlMode enums, bounded-wait
                                          HITL semantics, Ed25519-signed ledger

SYNERGY #3 (Port Shackle Governor as agentosirus's policy gate): `decide()`
and `Governor` here are the SINGLE canonical implementation; agentosirus's
`onitsirClient.ts` calls `POST /api/mission/:id/gate` (wrapping
`Governor.evaluate()`) rather than re-implementing any of this in TypeScript.

SYNERGY #6 (Single governance source of truth): `Verdict`/`DenyReason`/
`HitlMode` are enums here; `agentosirus-web/src/lib/shackle.ts` mirrors their
*string values only*, generated by `infra/scripts/sync-shackle-types.mjs`
from this module — never re-implementing `decide()`.

SYNERGY #9 (Ed25519 signing / audit ledger upgrade): `AuditLedger` gains
optional Ed25519 signing, ported from AgentOmega's `AuditLedger`.

SYNERGY #10 (Bounded-timeout HITL): `HitlMode` enum + `Governor.await_hitl()`
bounded-wait resolution logic, ported from AgentOmega's `_await_hitl()` /
`ShackleGovernor`. A HITL that never gets an operator response ALWAYS
resolves to safe DENY on timeout — it can never hang forever.

SYNERGY #11 (Declarative JSON-rule veto layer): `Governor.evaluate()` calls a
`ShackleValidator` (ported from ADROS in `shackle_rules.py`) as an
additional hard-veto check before returning ALLOW.

SYNERGY #12 (Additive ethics tag-weight scoring): `Governor.evaluate()`
accepts `tags` and additively scores them via `EthicsEngine` (ported from
ADROS in `ethics.py`); a below-threshold score forces DENY.

Shackle sits IN FRONT OF the Iron-Law verification gate:

    goal -> route -> [ Shackle: may this run? ] -> run -> [ Iron Law: did it pass? ] -> ship
"""
from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

try:
    from nacl.signing import SigningKey, VerifyKey
    from nacl.encoding import HexEncoder
    _HAVE_NACL = True
except Exception:  # pragma: no cover - optional dependency
    _HAVE_NACL = False

from .ethics import EthicsEngine
from .shackle_rules import ShackleValidator

Verdict = str  # "ALLOW" | "DENY" | "HITL"  (kept as str for backward-compat with ONITSIR callers)


class VerdictEnum(str, Enum):
    """SYNERGY #6/#10: enum form of Verdict, ported from AgentOmega's
    `Verdict` enum. `decide()` still returns plain strings for backward
    compatibility with ONITSIR's original callers/tests; this enum is what
    gets JSON-schema-exported for the TypeScript mirror."""
    ALLOW = "ALLOW"
    DENY = "DENY"
    HITL = "HITL"


class DenyReason(str, Enum):
    """SYNERGY #10: ported verbatim (as an enum of *reasons*, not free text)
    from AgentOmega's `app/shackle.py::DenyReason`. ONITSIR's original
    `decide()` returned free-text reason strings prefixed like
    'policy_violation:malformed_input' — those strings are preserved for
    backward compatibility, but every reason now also classifies into one of
    these canonical buckets via `classify_reason()` below."""
    UNSPECIFIED = "unspecified"
    BUDGET_EXHAUSTED = "budget_exhausted"
    MAX_REPEAT_EXCEEDED = "max_repeat_exceeded"
    CIRCUIT_OPEN = "circuit_open"
    WINDOW_EXCEEDED = "window_exceeded"
    GLOBAL_LIMIT = "global_limit"
    POLICY_VIOLATION = "policy_violation"
    AUTH_FAILED = "auth_failed"
    ETHICS_BELOW_THRESHOLD = "ethics_below_threshold"
    SHACKLE_RULE_VETO = "shackle_rule_veto"
    HITL_TIMEOUT = "hitl_timeout"


class HitlMode(str, Enum):
    """SYNERGY #10: ported from AgentOmega's `HitlMode` enum. Replaces
    ONITSIR's original bare `None | "always" | "on_threshold"` strings with a
    typed enum while remaining string-compatible."""
    NEVER = "never"
    ON_DENY = "on_deny"
    ON_THRESHOLD = "on_threshold"
    ALWAYS = "always"


def classify_reason(reason: str) -> DenyReason:
    """Map ONITSIR's historical free-text reason strings onto the canonical
    DenyReason enum, so both old and new callers get a stable classification."""
    if reason.startswith("policy_violation"):
        return DenyReason.POLICY_VIOLATION
    mapping = {
        "circuit_open": DenyReason.CIRCUIT_OPEN,
        "budget_exhausted": DenyReason.BUDGET_EXHAUSTED,
        "max_repeat_exceeded": DenyReason.MAX_REPEAT_EXCEEDED,
        "ethics_below_threshold": DenyReason.ETHICS_BELOW_THRESHOLD,
        "shackle_rule_veto": DenyReason.SHACKLE_RULE_VETO,
        "hitl_timeout": DenyReason.HITL_TIMEOUT,
    }
    return mapping.get(reason, DenyReason.UNSPECIFIED)


# ──────────────────────────────────────────────────────────────────────────
# Canonicalization + the policy decision surface (pure, stdlib-only)
# ──────────────────────────────────────────────────────────────────────────
def canonical_hash(params: Dict[str, Any]) -> str:
    """SHA-256 over canonical JSON: keys sorted, tight separators, UTF-8.

    NaN/Infinity and non-string keys are rejected (allow_nan=False), which
    callers treat as malformed input.
    """
    serialized = json.dumps(
        params, sort_keys=True, separators=(",", ":"),
        ensure_ascii=False, allow_nan=False,
    )
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def decide(
    config: Dict[str, Any],
    state: Dict[str, Any],
    call: Dict[str, Any],
) -> Tuple[Verdict, str]:
    """Return (verdict, reason) for a single action. Fail-closed by construction.

    Precedence (highest first) — unchanged from ONITSIR, this is the pure
    core the whole unified system depends on:
      1. malformed / non-canonicalizable input        -> DENY
      2. circuit already open                          -> DENY
      3. duplicate nonce (replay)                      -> DENY
      4. HITL transition contract (pending_transition) -> ALLOW/DENY/HITL
      5. budget exhausted                              -> DENY
      6. max repeat exceeded                           -> DENY
      7. HITL mode 'always'                            -> HITL
      8. HITL budget threshold                         -> HITL
      9. opaque / untestable context                   -> HITL (fail-closed)
     10. default                                       -> ALLOW
    """
    params: Dict[str, Any] = call.get("params", {}) or {}
    pending = state.get("pending_transition")

    # 1. malformed / non-canonicalizable input
    if params.get("__noncanonical__") is True:
        return ("DENY", "policy_violation:malformed_input")

    # 2. circuit already open
    if state.get("circuit_tripped") is True:
        return ("DENY", "circuit_open")

    # 3. duplicate nonce (replay)
    seen = state.get("seen_nonces") or []
    nonce = call.get("nonce")
    if nonce is not None and nonce in seen:
        if (
            pending
            and pending.get("resume_attempt") is True
            and pending.get("terminal_status") in ("rejected", "superseded")
        ):
            return ("DENY", "policy_violation:duplicate_resume_no_effect")
        return ("DENY", "policy_violation:duplicate_nonce")

    # 4. HITL transition contract
    if pending:
        decision = pending.get("decision")
        if decision == "approve":
            return ("ALLOW", "hitl_transition:approve")
        if decision == "reject":
            return ("DENY", "hitl_transition:reject")
        if decision == "modify":
            return ("ALLOW", "hitl_transition:modify_successor")
        if decision in ("defer", "escalate"):
            return ("HITL", "hitl_transition:defer_escalate")

    # 5. budget exhausted
    budget = config.get("budget_usd", 0) or 0
    remaining = state.get("budget_remaining_usd")
    if remaining is not None and remaining <= 0 and budget > 0:
        return ("DENY", "budget_exhausted")

    # 6. max repeat exceeded
    max_repeat = config.get("max_repeat_calls")
    repeat_counts = state.get("repeat_counts")
    last_tool = state.get("last_tool_name")
    if max_repeat is not None and repeat_counts and last_tool:
        rc = repeat_counts.get(call.get("tool_name"))
        if rc is not None and rc >= max_repeat and last_tool == call.get("tool_name"):
            return ("DENY", "max_repeat_exceeded")

    # 7. HITL always
    if config.get("hitl_mode") == "always":
        return ("HITL", "hitl_all_calls")

    # 8. HITL budget threshold
    if config.get("hitl_mode") == "on_threshold" and config.get("hitl_budget_threshold") is not None:
        initial = state.get("budget_initial_usd")
        if initial:
            frac = state.get("budget_remaining_usd", 0) / initial
            if frac <= config["hitl_budget_threshold"]:
                return ("HITL", "budget_threshold")

    # 9. opaque / untestable context
    if params.get("ctx") == "opaque":
        return ("HITL", "fail_closed:opaque_context")

    # 10. default allow
    return ("ALLOW", "within_thresholds")


# ──────────────────────────────────────────────────────────────────────────
# Tamper-evident, hash-chained audit ledger (+ SYNERGY #9 Ed25519 signing,
# ported from AgentOmega's app/shackle.py::AuditLedger)
# ──────────────────────────────────────────────────────────────────────────
GENESIS = "0" * 64


@dataclass(frozen=True)
class LedgerEntry:
    index: int
    at: float
    tool_name: str
    verdict: Verdict
    reason: str
    prev_hash: str
    entry_hash: str
    signature: str = ""
    verify_key: str = ""


class AuditLedger:
    """Append-only ledger where each entry commits to the previous one's hash.

    Any mutation of a past entry breaks the chain — `verify()` detects it.

    SYNERGY #9: optionally Ed25519-signs each entry (ported from AgentOmega).
    When `pynacl` is unavailable or no signing key is configured, signing is
    skipped and the ledger degrades gracefully to hash-chain-only integrity
    (still tamper-evident, just not signature-verifiable).
    """

    def __init__(self, signing_key_hex: Optional[str] = None) -> None:
        self._entries: List[LedgerEntry] = []
        self.signing_key = None
        self.verify_key_hex = ""
        if _HAVE_NACL:
            if signing_key_hex:
                self.signing_key = SigningKey(signing_key_hex, encoder=HexEncoder)
            else:
                self.signing_key = SigningKey.generate()
            self.verify_key_hex = self.signing_key.verify_key.encode(encoder=HexEncoder).decode()

    @staticmethod
    def _hash(index: int, at: float, tool_name: str, verdict: str,
              reason: str, prev_hash: str) -> str:
        return canonical_hash({
            "index": index, "at": at, "tool_name": tool_name,
            "verdict": verdict, "reason": reason, "prev_hash": prev_hash,
        })

    def append(self, tool_name: str, verdict: Verdict, reason: str,
               at: Optional[float] = None) -> LedgerEntry:
        at = time.time() if at is None else at
        index = len(self._entries)
        prev_hash = self._entries[-1].entry_hash if self._entries else GENESIS
        entry_hash = self._hash(index, at, tool_name, verdict, reason, prev_hash)
        signature = ""
        if self.signing_key is not None:
            signature = self.signing_key.sign(entry_hash.encode()).signature.hex()
        entry = LedgerEntry(
            index, at, tool_name, verdict, reason, prev_hash, entry_hash,
            signature=signature, verify_key=self.verify_key_hex,
        )
        self._entries.append(entry)
        return entry

    def verify(self) -> bool:
        """True iff the whole chain is intact (no entry has been tampered with)
        AND, for signed entries, the Ed25519 signature checks out."""
        prev = GENESIS
        for i, e in enumerate(self._entries):
            if e.index != i or e.prev_hash != prev:
                return False
            expected = self._hash(e.index, e.at, e.tool_name, e.verdict, e.reason, e.prev_hash)
            if expected != e.entry_hash:
                return False
            if e.signature and e.verify_key and _HAVE_NACL:
                try:
                    VerifyKey(e.verify_key, encoder=HexEncoder).verify(
                        e.entry_hash.encode(), bytes.fromhex(e.signature)
                    )
                except Exception:
                    return False
            prev = e.entry_hash
        return True

    def __len__(self) -> int:
        return len(self._entries)

    @property
    def entries(self) -> List[LedgerEntry]:
        return list(self._entries)

    @property
    def head(self) -> str:
        return self._entries[-1].entry_hash if self._entries else GENESIS


# ──────────────────────────────────────────────────────────────────────────
# Runtime Governor — live state + circuit breakers, wired to decide()
# ──────────────────────────────────────────────────────────────────────────
@dataclass
class GovernorConfig:
    budget_usd: float = 1.0
    max_repeat_calls: int = 3
    hitl_mode: Optional[str] = None            # None | "always" | "on_threshold"
    hitl_budget_threshold: Optional[float] = None
    hitl_timeout_s: float = 60.0               # SYNERGY #10: bounded HITL wait
    ethics_threshold: int = 0                  # SYNERGY #12
    signing_key_hex: Optional[str] = None      # SYNERGY #9
    shackle_rules_path: Optional[str] = None   # SYNERGY #11

    def as_dict(self) -> Dict[str, Any]:
        return {
            "budget_usd": self.budget_usd,
            "max_repeat_calls": self.max_repeat_calls,
            "hitl_mode": self.hitl_mode,
            "hitl_budget_threshold": self.hitl_budget_threshold,
        }


class Governor:
    """Stateful policy runtime. Feeds live telemetry into the pure decide()
    surface, additionally runs the ADROS-ported declarative veto rules
    (SYNERGY #11) and ADROS-ported ethics scoring (SYNERGY #12), and keeps a
    hash-chained (optionally Ed25519-signed, SYNERGY #9) audit ledger of
    every ruling.
    """

    def __init__(self, config: GovernorConfig | None = None) -> None:
        self.config = config or GovernorConfig()
        self.spent_usd: float = 0.0
        self.repeat_counts: Dict[str, int] = {}
        self.seen_nonces: List[str] = []
        self.circuit_tripped: bool = False
        self.last_tool_name: Optional[str] = None
        self.ledger = AuditLedger(signing_key_hex=self.config.signing_key_hex)
        self.ethics = EthicsEngine(threshold=self.config.ethics_threshold)
        self.validator = ShackleValidator.from_path(self.config.shackle_rules_path)
        self._pending_hitl: Optional[Dict[str, Any]] = None

    def _state(self) -> Dict[str, Any]:
        return {
            "circuit_tripped": self.circuit_tripped,
            "seen_nonces": list(self.seen_nonces),
            "budget_initial_usd": self.config.budget_usd,
            "budget_remaining_usd": max(self.config.budget_usd - self.spent_usd, 0.0),
            "repeat_counts": dict(self.repeat_counts),
            "last_tool_name": self.last_tool_name,
            "pending_transition": self._pending_hitl,
        }

    def evaluate(self, tool_name: str, *, cost_usd: float = 0.0,
                 nonce: Optional[str] = None,
                 params: Optional[Dict[str, Any]] = None,
                 tags: Optional[List[str]] = None) -> Tuple[Verdict, str]:
        """Rule on one action and record it. Updates live state first so budget
        and repeat breakers reflect *this* call, then consults decide(), then
        the ADROS-ported ethics score (#12) and declarative veto rules (#11).

        Precedence: decide() (resource/loop/replay/HITL contract) runs first
        because those are hard operational breakers; ethics/veto are content
        checks layered on top — a resource DENY is never masked by a content
        ALLOW, and a content veto can still DENY something decide() would
        otherwise ALLOW (vetoes always win, matching ADROS's SafetyKernel).
        """
        self.spent_usd += cost_usd
        self.repeat_counts[tool_name] = self.repeat_counts.get(tool_name, 0) + 1
        self.last_tool_name = tool_name
        tags = tags or []

        call: Dict[str, Any] = {"tool_name": tool_name, "params": params or {}}
        if nonce is not None:
            call["nonce"] = nonce

        verdict, reason = decide(self.config.as_dict(), self._state(), call)

        if nonce is not None and nonce not in self.seen_nonces:
            self.seen_nonces.append(nonce)

        # SYNERGY #11 + #12: only layer content checks on top when decide()
        # itself didn't already hard-DENY/HITL for resource/replay reasons.
        if verdict == "ALLOW":
            vetoes = self.validator.validate(tags=tags, params=params or {})
            if vetoes:
                verdict, reason = "DENY", f"shackle_rule_veto:{vetoes[0]}"
            else:
                score = self.ethics.score(tags)
                if tags and score < self.config.ethics_threshold:
                    verdict, reason = "DENY", f"ethics_below_threshold:{score}"

        if verdict == "DENY":
            self.circuit_tripped = True

        self.ledger.append(tool_name, verdict, reason)
        return verdict, reason

    def request_hitl(self, tool_name: str, reason: str) -> None:
        """Register a pending HITL transition awaiting an operator decision."""
        self._pending_hitl = {"tool_name": tool_name, "reason": reason, "decision": None}

    def resolve_hitl(self, decision: str) -> None:
        """SYNERGY #10: operator resolves a pending HITL as approve/reject/modify.
        Called by `onitsir-server`'s `/api/mission/:id/hitl` route (mirroring
        AgentOmega's HITL_RESPONSE WS message) or directly in tests."""
        if self._pending_hitl is not None:
            self._pending_hitl["decision"] = decision

    def hitl_timeout(self) -> Tuple[Verdict, str]:
        """SYNERGY #10: bounded-wait timeout resolution — ported from
        AgentOmega's `_await_hitl()`. If the operator never responds within
        `hitl_timeout_s`, the call ALWAYS resolves to safe DENY; a mission can
        never hang forever waiting on a human who isn't there."""
        self._pending_hitl = None
        self.circuit_tripped = True
        reason = "hitl_timeout"
        self.ledger.append("hitl_wait", "DENY", reason)
        return ("DENY", reason)

    def clear_hitl(self) -> None:
        self._pending_hitl = None

    @property
    def remaining_usd(self) -> float:
        return max(self.config.budget_usd - self.spent_usd, 0.0)
